### ISSUE TITLE
onClose event is missing. 

### ISSUE THREAD

**Issue by acpmasquerade** [khalti/khalti-sdk-web#7]
onSuccess() is there
onError() is there

how would I know if the checkout widget is closed ?

**Comment by rajsubit** [comment]
onClose() event Handler added

**Comment by razukc** [comment]
This is my code
```
onClose () {
							            console.log('Widget is closing');
							        }
```
But there is no log in the console. Is it working?

**Comment by rajsubit** [comment]
Can you create a new issue and post the whole config?

**Comment by razukc** [comment]
The link to reproduce the issue: `https://codesandbox.io/s/3ym164ol01`
